site_name: Holiwis
site_url: https://kryeit.wiki
repo_url: https://github.com/Kryeit/holiwis
nav:
  - Home: index.md
  - Survival:
      - Season 3:
          - Getting Started: server/getting-started.md
          - Posts:
              - Commands: posts/commands.md
              - History Timeline: posts/history.md
          - Claims:
              - Commands: claims/commands.md
          - Specs: server/specs.md
  - Our Mods:
      - About: homemade/about.md
      - Telepost: homemade/telepost.md
      - 'Create: Missions': homemade/missions.md
  - Contributing: contributing.md
theme:
    name: material
plugins:
   - search
   - glightbox:
       touchNavigation: true
       loop: false
       effect: fade
       slide_effect: slide
       zoomable: true
       draggable: true
       auto_caption: true
       caption_position: bottom
       background: transparent
       shadow: true
       manual: false
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.blocks.caption