name: ci

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip and MkDocs cache
        uses: actions/cache@v4
        with:
          # runner.os and hashFiles() are valid here
          key: mkdocs-${{ runner.os }}-pip-mkdocs-${{ hashFiles('requirements.txt') }}
          path: |
            .cache
            ~/.cache/pip

            - name: Install MkDocs & Plugins
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-singlefile-plugin

      - name: Build & Deploy Single-File Site
        run: |
          # build into `site/` as one big index.html
          mkdocs build --clean --singlefile
          # push it to gh-pages
          mkdocs gh-deploy --force --message "ci: deploy single-file site"

      - name: Build & Deploy
        run: mkdocs gh-deploy --force
